POST http://localhost:3000/datasheets HTTP/1.1
Content-Type: application/json

{
	"url": "https://xyx.xom"
}

###

POST http://localhost:3000/designs HTTP/1.1
Content-Type: application/json

{
	"name": "Insulator",
	"html": "<h1>Insulator</h1>"
}

###

GET http://localhost:3000/logins/mr.siddique@gmail.com HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/datasheets HTTP/1.1
Content-Type: application/json